### ISSUE TITLE
Update Google Analytics tracking before 7/1/2023

### ISSUE THREAD

**Issue by tclayton33** [emory-libraries/librarysearch-enhance#25]
Universal Analytics is being replaced by Google Analytics 4. On July 1, 2023, standard Universal Analytics properties will stop processing new hits; we need to switch over to Google Analytics 4 before then. 

After July 1, 2023, we'll be able to access our previously processed data in our Universal Analytics property for at least six months; for longer term access we'll need to export this data.

More details:
[https://support.google.com/analytics/answer/11583528](url)
[https://support.google.com/analytics/answer/11583528#export](url)

Tasks:
- [x] update to GA4 property
- [x] test if custom event tracking still works
- [x] recreate reports
- [x] export Universal Analytics data
- [x] identify other remediations needed
- [x] check on warning message ("this property is not fully set up...here is [the fix](https://support.google.com/analytics/answer/10110290)")

Reports to recreate:
- [x] Views by Format
- [x] Views by Library
- [x] Facets Expanded 
- [x] Facets Clicked
- [x] Search Fields
- [x] Advanced Search
- [x] Search Terms
- [x] Pages Viewed (built in as the "Engagement - Pages and Screens" report)
- [x] Format dashboard (no reformatting required at this time)

This issue relates to dlp-curate issue 1803 [https://app.zenhub.com/workspaces/digital-library-project-5bf484ae4b5806bc2bf6875b/issues/gh/emory-libraries/dlp-curate/1803](url)

Additional info: Value score = 6
